const D=require('./_drv'); const fs=require('fs'),path=require('path');
const F='form:j_idt115';
const a=Object.fromEntries(process.argv.slice(2).map(x=>x.replace(/^--/,'').split('=')));
const PAGE=a.page||'/pages/pedidosVendedores', CUMP=a.cump||'Facturado', CUR=a.cur||'US$';
const D1=a.d1||'01/08/2026', D2=a.d2||'31/08/2026', TAG=a.tag||'C-IND';
(async()=>{const {pg}=await D.attach();
 await D.goto(pg,PAGE); await pg.waitForTimeout(2500);
 console.log('cump='+await D.pick(pg,`${F}:cumplimiento`,CUMP));
 console.log('cur='+await D.pick(pg,`${F}:idCurrency`,CUR));
 await pg.evaluate(([f,x,y])=>{const a=document.getElementById(f+':dateB_input');if(a)a.value=x;const b=document.getElementById(f+':dateF_input');if(b)b.value=y;},[F,D1,D2]);
 const st=await pg.evaluate((f)=>({vend:document.getElementById(f+':vendedor_input')?.value,cump:document.getElementById(f+':cumplimiento_input')?.value,cur:document.getElementById(f+':idCurrency_input')?.value,d1:document.getElementById(f+':dateB_input')?.value,d2:document.getElementById(f+':dateF_input')?.value}),F);
 console.log('ESTADO='+JSON.stringify(st));
 await pg.$eval(`[id="${F}:ajax"]`,e=>e.click()); await pg.waitForTimeout(10000);
 await D.shot(pg,TAG);
 const t=await D.txt(pg); const i=t.indexOf('Detalle de Transacciones');
 console.log('---TXT---\n'+t.slice(i>=0?i:0,(i>=0?i:0)+2500));
 const tabs=await pg.evaluate(()=>[...document.querySelectorAll('table')].map(tb=>[...tb.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(c=>c.innerText.trim().replace(/\s+/g,' ')).join(' | ')).join('\n')).filter(x=>x.length>10));
 fs.writeFileSync(path.join(__dirname,'_'+TAG+'.txt'), t + '\n\n=== TABLAS ===\n' + tabs.join('\n---\n'));
 console.log('---TABLAS---\n'+tabs.join('\n---\n').slice(0,2500));
 process.exit(0);})();
